#!/bin/bash

function print_usage() {
    echo -e "\nUsage:\n\t`basename $0` <domain> on | off\n"
    exit 2
}

if [ "$EUID" -ne 0 ]; then
    sudo $0 $@
    exit 1
fi

if [ "$1" = "" -a "$2" = "" ]; then
    print_usage
fi

DOMAIN=$1
MODE=$2
DOC_ROOT="/home/web/repo/files/${DOMAIN}"
MAINT_PAGE="${DOC_ROOT}/maintenance.html"
NO_MAINT_PAGE="${DOC_ROOT}/no-maintenance.html"
SAMPLE_MAINT_PAGE="${DOC_ROOT}/sample-maintenance.html"

if [ ! -d ${DOC_ROOT} ]; then
    echo "The directory ${DOC_ROOT} does not exist"
    exit
fi

if [ "${MODE}" = "on" ]; then
    if [ -f ${MAINT_PAGE} ]; then
        echo -e "\nSite ${DOMAIN} is already in maintenance mode\n"
    elif [ ! -f ${NO_MAINT_PAGE} ];then
        echo -e "\n***********************************************************************"
        echo -e "*"
        echo -e "*  The Maintence mode page not defined."
        echo -e "*"
        echo -e "*  Please create a file called:"
        echo -e "*"
        echo -e "*     ${NO_MAINT_PAGE}"
        echo -e "*"
        echo -e "*  This page will be displayed to users when you enter maintenance mode"
        echo -e "***********************************************************************\n\n"

        if [ -f ${SAMPLE_MAINT_PAGE} ]; then
            OK=""

            while [ "${OK}" != "y" -a "${OK}" != "Y" -a  "${OK}" != "n" -a  "${OK}" != "N" ]; do
                echo -e "\rOk to clone the sample maintenance file (y/n) \c"
                read OK
            done

            if [ "${OK}" = "y" -o "${OK}" = "Y" ]; then
                cp ${SAMPLE_MAINT_PAGE} ${NO_MAINT_PAGE}
                echo -e "\nThe maintenance page \n\n\t${NO_MAINT_PAGE}\n"
                
                echo -e "has been created.  Modify as appropriate an run this command again\n"
            fi
        fi
    else
        mv ${NO_MAINT_PAGE} ${MAINT_PAGE}
    fi
elif [ "${MODE}" = "off" ]; then
    if [ ! -f ${MAINT_PAGE} ]; then
        echo -e "\nSite ${DOMAIN} is not in maintenance mode\n"
    else
        mv ${MAINT_PAGE} ${NO_MAINT_PAGE}
    fi
else
    print_usage
fi
